### ISSUE TITLE
fix the following hard-coded pieces

### ISSUE THREAD

**Issue by LilySnow** [rhinowarrior/swifttcr#1]
Currently: 

1. The pMHC structures are named as chain A (MHC class I α1), B (MHC class I β2 Microglobulin), and C (peptide). Similarly, the TCR α and β chains are denoted as chains D and E, respectively.

**Comment by rhinowarrior** [comment]
We now change the chainIDs of the input TCR and pMHC in the initial_placement.py. This is done by using the alignment between the target structure and the reference structures.
