### ISSUE TITLE
some generated models shows dashes in pymol 

### ISSUE THREAD

**Issue by LilySnow** [rhinowarrior/swifttcr#15]
when I check 5c07 merged_476.pdb in pymol, its TCR shows dashes: 
<img width="403" alt="image" src="https://github.com/user-attachments/assets/c417316d-c30e-4fdc-9ea9-2c4430289acf">

I remember it is caused by wrongly ordered residues. Can you check and fix this bug?

**Comment by rhinowarrior** [comment]
This issue was caused by the order of the normal residues and alternative residues. To solve this problem we reordered the alternative residues and normal residues.

This was the order at first, for example:
11
11A
12

This is the order now:
11A
11
12
