### ISSUE TITLE
change prepare.py so it reorders the alternative residues and normale residues correctly

### ISSUE THREAD

**Issue by rhinowarrior** [rhinowarrior/swifttcr#24]
Somewhere in prepare.py or in the scripts it uses, the pdb files are sorted in a way that causes the alternative residues to be placed after the normal residues which caused the dashed lines when viewed in Pymol. to solve this for now the choice was made to make a new script that opens the files reads them and flips the alternative residues and the normal residues. So that the alternative residues are before the normal residues. But in the future i think it is better to find what might be causing the problem in prepare.py and change it in there.

**Comment by JanAarts** [comment]
Are you sure it is because prepare.py? I thought it was caused by pdb
tools, pdb_sort.

Op do 10 okt 2024 14:44 schreef rhinowarrior ***@***.***>:

**Comment by rhinowarrior** [comment]
We tested the pipeline step for step and both seemed to cause the same problems. So they both caused the problem. But i have solved the issue for now by fixing the residue ordering of both the pMHC and the TCR after prepare.py and after that i avoid using pdb_sort and pdb_tidy in the TCR part of merge_pdb.py and this seemed to solve the problems.

**Comment by rhinowarrior** [comment]
Now we use the script flip_alternative.py to do this
